config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,        only: [:new, :create, :destroy]
  resources :microposts,      only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :password_resets
  resources :products do
    member do
      get :following
    end
  end
  resources :orders
  resources :suppliers
  resources :supplierproducts do
    member do
      get :followers
    end
  end
  resources :purchases
  resources :purchaselines

  root to: 'static_pages#app'

  match '/board',             to: 'static_pages#home'
  match '/signup',            to: 'users#new'
  match '/signin',            to: 'sessions#new'
  match '/signout',           to: 'sessions#destroy', via: :delete
  match '/help',              to: 'static_pages#help'
  match '/about',             to: 'static_pages#about'
  match '/contact',           to: 'static_pages#contact'

end

app/models/supplierproduct.rb
class Supplierproduct < ActiveRecord::Base
  attr_accessible :ean, :name, :price, :sku, :stock, :supplier_id
  belongs_to :supplier
  has_many :reverse_productrelationships, foreign_key: "followed_id", class_name: "Productrelationship", dependent: :destroy
  has_many :followers, through: :reverse_productrelationships, source: :follower

  validates :supplier_id, presence: true

  searchable do
    text :ean, :name, :sku
    string :supplier_id
  end
end

app/controllers/supplierproducts_controller.rb
class SupplierproductsController < ApplicationController

	helper_method :sort_column, :sort_direction

	def index
		@user = current_user
			@search = @user.supplierproducts.search do
			fulltext params[:search]
			facet(:supplier_id)
			with(:supplier_id, params[:supplier_id]) if params[:supplier_id].present?
		end
		@supplierproducts = @search.results
	end

	def show
		@supplier = Supplier.find(params[:id])
		@search = @supplier.supplierproducts.search do
			fulltext params[:search]
		end
		@supplierproducts = @search.results
	end

	private

		def sort_column
			Supplierproduct.column_names.include?(params[:sort]) ? params[:sort] : "name"
		end
		
		def sort_direction
			%w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
		end
end

app/helpers/supplierproducts_helper.rb
module SupplierproductsHelper
end

app/views/supplierproducts/_supplierproducts.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= hidden_field_tag :supplier_id, params[:supplier_id] %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= sortable "sku", "SKU" %></th>
      <th><%= sortable "name", "Product name" %></th>
      <th><%= "Connection" %></th>
      <th><%= sortable "stock", "Stock" %></th>
      <th><%= sortable "price", "Price" %></th>
      <th><%= sortable "ean", "EAN number" %></th>
    </tr>
  </thead>
  	<% for supplierproduct in @supplierproducts %>
  <tbody>
    <tr>
      <td><%= supplierproduct.sku %></td>
      <td><%= supplierproduct.name %></td>
      <td><%= render 'product_search' %></td>
      <td><%= supplierproduct.stock %></td>
      <td><%= supplierproduct.price %></td>
      <td><%= supplierproduct.ean %></td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/supplierproducts/index.html.erb
<%= form_tag supplierproducts_path, :method => :get, :id => "supplierproducts_search" do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: "Search by SKU, product name & EAN number..." %>
  </p>
  <div id="supplierproducts"><%= render 'supplierproducts' %></div>
<% end %>

<div id="facets">
  <h3>Supplier</h3>
  <ul>
    <% for row in @search.facet(:supplier_id).rows %>
      <li>
        <% if params[:supplier_id].blank? %>
          <%= link_to row.value, :supplier_id => row.value %> (<%= row.count %>)
        <% else %>
          <strong><%= row.value %></strong> (<%= link_to "Show all suppliers", :supplier_id => nil %>)
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/supplierproducts/index.js.erb
$('#supplierproducts').html('<%= escape_javascript(render("supplierproducts")) %>');