config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,        only: [:new, :create, :destroy]
  resources :microposts,      only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :password_resets
  resources :products do
    member do
      get :following
    end
  end
  resources :orders
  resources :suppliers
  resources :supplierproducts do
    member do
      get :followers
    end
  end
  resources :purchases
  resources :purchaselines

  root to: 'static_pages#app'

  match '/board',             to: 'static_pages#home'
  match '/signup',            to: 'users#new'
  match '/signin',            to: 'sessions#new'
  match '/signout',           to: 'sessions#destroy', via: :delete
  match '/help',              to: 'static_pages#help'
  match '/about',             to: 'static_pages#about'
  match '/contact',           to: 'static_pages#contact'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :ean, :name, :price, :stock, :sku
  belongs_to :user
  has_many :productrelationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_supplierproducts, through: :productrelationships, source: :followed

  validates :user_id, :sku, :name, presence: true

  searchable do
    text :ean, :sku, :name
  end

  def follow!(supplierproduct)
    productrelationships.create!(followed_id: supplierproduct.id)
  end

	def following?(supplierproduct)
  	productrelationships.find_by_followed_id(supplierproduct.id)
	end

	def unfollow!(supplierproduct)
		productrelationships.find_by_followed_id(supplierproduct.id).destroy
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	helper_method :sort_column, :sort_direction

	def index
		@user = current_user
			@search = @user.products.search do
			fulltext params[:search]
#			order_by sort_column, sort_direction
		end
		@products = @search.results
	end

	private

		def sort_column
			Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
		end
		
		def sort_direction
			%w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
		end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.hmtl.erb
<li>
    <%= product.sku %>, <%= product.name %>
</li>

Currently not working

app/views/products/_products.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= sortable "sku", "SKU" %></th>
      <th><%= sortable "name", "Product name" %></th>
      <th><%= sortable "stock", "Stock" %></th>
      <th><%= sortable "price", "Price" %></th>
      <th><%= sortable "ean", "EAN number" %></th>
    </tr>
  </thead>
  	<% for product in @products %>
  <tbody>
    <tr>
      <td><%= product.sku %></td>
      <td><%= link_to product.name, product_path(product) %></td>
      <td><%= product.stock %></td>
      <td><%= product.price %></td>
      <td><%= product.ean %></td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/products/index.html.erb
<%= form_tag products_path, :method => :get, :id => "products_search" do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: "Search by SKU, product name & EAN number..." %>
  </p>
  <div id="products"><%= render 'products' %></div>
<% end %>

app/views/products/index.js.erb
$('#products').html('<%= escape_javascript(render("products")) %>');

app/views/products/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/product_relationship_stats' %>
    </section>
  </aside>
</div>