config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,        only: [:new, :create, :destroy]
  resources :microposts,      only: [:create, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :password_resets
  resources :products do
    member do
      get :following
    end
  end
  resources :orders
  resources :suppliers
  resources :supplierproducts do
    member do
      get :followers
    end
  end
  resources :purchases
  resources :purchaselines

  root to: 'static_pages#app'

  match '/board',             to: 'static_pages#home'
  match '/signup',            to: 'users#new'
  match '/signin',            to: 'sessions#new'
  match '/signout',           to: 'sessions#destroy', via: :delete
  match '/help',              to: 'static_pages#help'
  match '/about',             to: 'static_pages#about'
  match '/contact',           to: 'static_pages#contact'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user

  validates :content, presence: true, length: { maximum: 2000 }
  validates :user_id, presence: true

  default_scope order: 'microposts.created_at DESC'

  def self.from_users_followed_by(user)
  	followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
  	where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)
  end
end

app/models/oder_line.rb
class OderLine < ActiveRecord::Base
  attr_accessible :order_number, :price, :product_sku, :quantity
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :country, :date, :mail, :name, :number, :payment, :phone, :zip_code
  belongs_to :user
  has_many :orderlines, dependent: :destroy

  validates :user_id, :number, presence: true

  searchable do
    text :address, :address2, :city, :date, :mail, :name, :number, :phone, :zip_code
  end
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  attr_accessible :order_id, :price_pr_unit, :product_sku, :quantity_delivered, :quantity_invoiced, :quantity_ordered
end

app/models/orderline.rb
class Orderline < ActiveRecord::Base
  attr_accessible :ean, :name, :order_id, :price, :product_id, :qty_ordered, :sku
  belongs_to :order

  validates :order_id, :qty_ordered, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :ean, :name, :price, :stock, :sku
  belongs_to :user
  has_many :productrelationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_supplierproducts, through: :productrelationships, source: :followed

  validates :user_id, :sku, :name, presence: true

  searchable do
    text :ean, :sku, :name
  end

  def follow!(supplierproduct)
    productrelationships.create!(followed_id: supplierproduct.id)
  end

	def following?(supplierproduct)
  	productrelationships.find_by_followed_id(supplierproduct.id)
	end

	def unfollow!(supplierproduct)
		productrelationships.find_by_followed_id(supplierproduct.id).destroy
	end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  attr_accessible :date, :delivery_number, :invoice_number, :shipping_fee, :state, :supplier_id
  belongs_to :supplier
  has_many :purchaselines, dependent: :destroy

  validates :supplier_id, presence: true

  searchable do
    text :supplier_id, :id, :state
  end
end

app/models/purchaseline.rb
class Purchaseline < ActiveRecord::Base
  attr_accessible :ean, :name, :price, :purchase_id, :qty_purchased, :qty_received, :sku
  belongs_to :purchase

  validates :purchase_id, :qty_purchased, presence: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :country, :currency, :mail, :name, :zip_code
  belongs_to :user
  has_many :supplierproducts
  has_many :purchases

  validates :user_id, presence: true

  searchable do
    text :name
  end  	
end

app/models/supplierproduct.rb
class Supplierproduct < ActiveRecord::Base
  attr_accessible :ean, :name, :price, :sku, :stock, :supplier_id
  belongs_to :supplier
  has_many :reverse_productrelationships, foreign_key: "followed_id", class_name: "Productrelationship", dependent: :destroy
  has_many :followers, through: :reverse_productrelationships, source: :follower

  validates :supplier_id, presence: true

  searchable do
    text :ean, :name, :sku
    string :supplier_id
  end
end

app/models/user.rb
class User < ActiveRecord::Base 
	attr_accessible :name, :email, :password, :password_confirmation
	has_secure_password
	has_many :microposts, dependent: :destroy
	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed
	has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
	has_many :followers, through: :reverse_relationships, source: :follower
	has_many :products, dependent: :destroy
	has_many :orders, dependent: :destroy
	has_many :orderlines, :through => :orders
	has_many :suppliers, dependent: :destroy
	has_many :supplierproducts, :through => :suppliers
	has_many :purchases, :through => :suppliers

	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
#	validates :password, length: { minimum: 6 } # outcommented until I have figured out why it disrupts the send_password_reset
#	validates :password_confirmation, presence: true # outcommented until I have figured out why it disrupts the send_password_reset

	def feed
		Micropost.from_users_followed_by(self)
	end

	def following?(other_user)
		relationships.find_by_followed_id(other_user.id)
	end

	def follow!(other_user)
		relationships.create!(followed_id: other_user.id)
	end

	def unfollow!(other_user)
		relationships.find_by_followed_id(other_user.id).destroy
	end

	def send_password_reset
		self.password_reset_token = SecureRandom.urlsafe_base64
		self.password_reset_sent_at = Time.zone.now
		save!
		UserMailer.password_reset(self).deliver
	end

	private
		
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/helpers/microposts_helper.rb
module MicropostsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_path, notice: "Please sign in."
		end
	end

	def sign_out
		current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.fullpath
	end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 60 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://boribana.com/" target="_blank"></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to "ERP", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
            <% if signed_in? %>
              <li><%= link_to "Products", products_path %></li>
              <li><%= link_to "Orders", orders_path %></li>
              <li><%= link_to "Purchases", purchases_path %></li>
              <li><%= link_to "Suppliers", suppliers_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Discussion board", board_path %></li>
                <li><%= link_to "My users", users_path if current_user.admin? %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= gravatar_for(feed_item.user) %>
    <span class="user">
     <% if current_user.admin? %>
      <%= link_to feed_item.user.name, feed_item.user %>
    <% else %>
      <%= feed_item.user.name %>
    <% end %>
    </span>
    <span class="content"><%= wrap(feed_item.content) %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method:  :delete,
                                     confirm: "You sure?",
                                     title:   feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new contribution..." %>
  </div>
  <%= f.submit "Post contribution", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_product_relationship_stats.html.erb
<% @product = Product.find(params[:id]) %>
<%= @product.followed_supplierproducts.count %> following

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following", class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_supplierproduct_relationship_stats.html.erb
<% @supplierproduct = Supplierproduct.find(params[:id]) %>
<%= @supplierproduct.followers.count %> followers

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 90 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "View my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "contribution") %>
</span>